// <auto-generated />
using System;
using FiscalDocumentationService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiscalDocumentationService.Migrations
{
    [DbContext(typeof(FiscalDocumentationDbContext))]
    [Migration("20260109180016_se agrego campo de iva condition type en fiscal document")]
    partial class seagregocampodeivaconditiontypeenfiscaldocument
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiscalDocumentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DispatchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FiscalDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VATAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VATBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VATId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FiscalDocumentId");

                    b.ToTable("FiscalDocumentItems");
                });

            modelBuilder.Entity("FiscalDocumentationService.Infrastructure.Models.FiscalDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ArcaCorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArcaEnvironment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArcaErrorsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArcaLastInteractionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArcaObservationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArcaRequestJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArcaResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArcaStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BuyerDocumentNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("BuyerDocumentType")
                        .HasColumnType("int");

                    b.Property<string>("CAE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CAEExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmissionProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExemptAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("InvoiceFrom")
                        .HasColumnType("bigint");

                    b.Property<long>("InvoiceTo")
                        .HasColumnType("bigint");

                    b.Property<int>("InvoiceType")
                        .HasColumnType("int");

                    b.Property<string>("IssuerTaxId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonTaxableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherTaxesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PointOfSale")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverVatConditionId")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("VATAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FiscalDocuments");
                });

            modelBuilder.Entity("FiscalDocumentItem", b =>
                {
                    b.HasOne("FiscalDocumentationService.Infrastructure.Models.FiscalDocument", "FiscalDocument")
                        .WithMany("Items")
                        .HasForeignKey("FiscalDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FiscalDocument");
                });

            modelBuilder.Entity("FiscalDocumentationService.Infrastructure.Models.FiscalDocument", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
