// <auto-generated />
using System;
using AccountingService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingService.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20251008155507_arreglos minimos en accounting")]
    partial class arreglosminimosenaccounting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ledger")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingService.Infrastructure.Models.Common.NumberingSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NextNumber")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NumberingSequences", "ledger");
                });

            modelBuilder.Entity("AccountingService.Infrastructure.Models.Ledger.Allocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreditDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("DebitDocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CreditDocumentId");

                    b.HasIndex("DebitDocumentId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("Allocations", "ledger", t =>
                        {
                            t.HasCheckConstraint("CK_Allocations_Amount_Positive", "[AmountBase] > 0");

                            t.HasCheckConstraint("CK_Allocations_SourceShape", "(\r\n                            (Source = 1 AND ReceiptId IS NOT NULL AND CreditDocumentId IS NULL) OR\r\n                            (Source = 2 AND CreditDocumentId IS NOT NULL AND ReceiptId IS NULL)\r\n                          )");
                        });
                });

            modelBuilder.Entity("AccountingService.Infrastructure.Models.Ledger.LedgerDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DisplayNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FxRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<byte>("PartyType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("SourceKind")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TotalBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOriginal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId")
                        .IsUnique()
                        .HasDatabaseName("UX_Documents_ReceiptId")
                        .HasFilter("[ReceiptId] IS NOT NULL");

                    b.HasIndex("SourceKind", "SourceDocumentId")
                        .IsUnique()
                        .HasDatabaseName("UX_Documents_SourceKind_SourceId")
                        .HasFilter("[SourceKind] IS NOT NULL AND [SourceDocumentId] IS NOT NULL");

                    b.HasIndex("PartyType", "PartyId", "Status", "Kind", "DocumentDate")
                        .HasDatabaseName("IX_Documents_Party_Status_Kind_Date");

                    b.ToTable("Documents", "ledger");
                });

            modelBuilder.Entity("AccountingService.Infrastructure.Models.Ledger.PaymentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountOriginal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BankAccountId")
                        .HasColumnType("int");

                    b.Property<bool?>("CheckIsThirdParty")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CheckIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckIssuerBankCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckIssuerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckIssuerTaxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CheckPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Method")
                        .HasColumnType("tinyint");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptPayments", "ledger");
                });

            modelBuilder.Entity("AccountingService.Infrastructure.Models.Ledger.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FxRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Number")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<byte>("PartyType")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TotalBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOriginal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PartyType", "PartyId", "Date");

                    b.ToTable("Receipts", "ledger");
                });

            modelBuilder.Entity("AccountingService.Infrastructure.Models.Ledger.Allocation", b =>
                {
                    b.HasOne("AccountingService.Infrastructure.Models.Ledger.LedgerDocument", "CreditDocument")
                        .WithMany()
                        .HasForeignKey("CreditDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AccountingService.Infrastructure.Models.Ledger.LedgerDocument", "DebitDocument")
                        .WithMany()
                        .HasForeignKey("DebitDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccountingService.Infrastructure.Models.Ledger.Receipt", "Receipt")
                        .WithMany("Allocations")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreditDocument");

                    b.Navigation("DebitDocument");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("AccountingService.Infrastructure.Models.Ledger.LedgerDocument", b =>
                {
                    b.HasOne("AccountingService.Infrastructure.Models.Ledger.Receipt", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("AccountingService.Infrastructure.Models.Ledger.PaymentLine", b =>
                {
                    b.HasOne("AccountingService.Infrastructure.Models.Ledger.Receipt", "Receipt")
                        .WithMany("PaymentLines")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("AccountingService.Infrastructure.Models.Ledger.Receipt", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("PaymentLines");
                });
#pragma warning restore 612, 618
        }
    }
}
